Mallapp\GeobitsBundle\Entity\Geobit:
    type: mappedSuperclass
    table: geobit
    id: {  }
    fields:
        latitude:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        longitude:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        generatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        changedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        active:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
