<?php

namespace Mallapp\GeobitsBundle\Repository;

/**
 * GeobitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeobitRepository extends \Doctrine\ORM\EntityRepository
{
}
