<?php

namespace Mallapp\GeobitsBundle\Repository;

/**
 * UserRetrievalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRetrievalsRepository extends \Doctrine\ORM\EntityRepository
{
}
